### ISSUE TITLE
Argument Error: erlang.bit_size(nil)

### ISSUE THREAD

**Issue by Arsca** [luizParreira/pamela#24]
Hi,
Trying to compile the project but get stucked to this error:

> [info] Running PamelaWeb.Endpoint with Cowboy using http://0.0.0.0:4000
[debug] QUERY OK source="trading_sessions" db=2.8ms
SELECT t0."id", t0."name", t0."running", t0."telegram_user_id", t0."command_id", t0."inserted_at", t0."updated_at" FROM "trading_sessions" AS t0 WHERE (t0."telegram_user_id" IS NULL AND t0."running" IS NULL) []
[error] GenServer #PID<0.428.0> terminating
** (ArgumentError) argument error
    :erlang.bit_size(nil)
    (nadia) lib/nadia/api.ex:9: Nadia.API.build_url/1
    (nadia) lib/nadia/api.ex:93: Nadia.API.request/3
    (pamela) lib/pamela/message_handler.ex:7: Pamela.MessageHandler.handle/0
    (pamela) lib/pamela/periodic_task.ex:15: Pamela.PeriodicTask.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :work
State: %{task: #Function<0.71608958/0 in Pamela.Application.start/2>}

- macOS 10.13.6

**Comment by luizParreira** [comment]
@Arsca Hm, this seems to be happening when you try to get new updates from the Telegram server. Have you gone through the configuration steps and created a telegram bot, in order to have a new token? 🤔
